# Generated by Django 4.2 on 2025-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_date_added_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            # field=models.SlugField(default='default-slug', unique=True),
            field=models.SlugField(default='default-slug', unique=False),
        ),
    ]
